### ISSUE TITLE
C++ game engine in lua????

### ISSUE THREAD

**Issue by LetMeCodeCInCPP** [JJoeDev/E2DE#1]
Where is the functionality of the game engine and what graphics standard does this use?

**Comment by JJoeDev** [comment]
The lua part is simply for premake because I got mad at cmake. There currently is no functionality as I am still getting everything set up. As of now the plan is to use SDL2 for windowing and input handeling and implement my own stuff as I feel the need for it. And once I get to the audio part I will have to figure out how OpenAL works

**Comment by LetMeCodeCInCPP** [comment]
So you are using SDL2 renderer?
Why would you not SDL2 with opengl or similar?

**Comment by LetMeCodeCInCPP** [comment]
another question is why use SDL2 and not use the inbuilt audio system?

**Comment by JJoeDev** [comment]
The answer to that is quite simple. I had no idea SDL2 had inbuilt audio lol. Well guess I don't have to use OpenAL anyways then
